import { describe, expect, test } from "@jest/globals";
import { sortByRatingMax } from "../modules/filter/compose/sort-by-rating-max";
import { filterStore } from "../modules/filter/data/filter-store";

describe("sort module", () => {
  filterStore.sort = "ratingmax";
  const send = [
    {
      id: 6,
      title: "MacBook Pro",
      description: "",
      price: 1749,
      discountPercentage: 11.02,
      rating: 4.57,
      stock: 83,
      brand: "Apple",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.png",
      images: [],
    },
    {
      id: 7,
      title: "Samsung Galaxy Book",
      description: "",
      price: 1499,
      discountPercentage: 4.15,
      rating: 4.25,
      stock: 50,
      brand: "Samsung",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      images: [],
    },
    {
      id: 8,
      title: "Microsoft Surface Laptop 4",
      description: "",
      price: 1499,
      discountPercentage: 10.23,
      rating: 4.43,
      stock: 68,
      brand: "Microsoft Surface",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
      images: [],
    },
    {
      id: 9,
      title: "Infinix INBOOK",
      description: "",
      price: 1099,
      discountPercentage: 11.83,
      rating: 4.54,
      stock: 96,
      brand: "Infinix",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
      images: [],
    },
    {
      id: 10,
      title: "HP Pavilion 15-DK1056WM",
      description: "",
      price: 1099,
      discountPercentage: 6.18,
      rating: 4.44,
      stock: 89,
      brand: "HP Pavilion",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
      images: [],
    },
  ];
  const expected = [
    {
      id: 7,
      title: "Samsung Galaxy Book",
      description: "",
      price: 1499,
      discountPercentage: 4.15,
      rating: 4.25,
      stock: 50,
      brand: "Samsung",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      images: [],
    },
    {
      id: 8,
      title: "Microsoft Surface Laptop 4",
      description: "",
      price: 1499,
      discountPercentage: 10.23,
      rating: 4.43,
      stock: 68,
      brand: "Microsoft Surface",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
      images: [],
    },
    {
      id: 10,
      title: "HP Pavilion 15-DK1056WM",
      description: "",
      price: 1099,
      discountPercentage: 6.18,
      rating: 4.44,
      stock: 89,
      brand: "HP Pavilion",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
      images: [],
    },
    {
      id: 9,
      title: "Infinix INBOOK",
      description: "",
      price: 1099,
      discountPercentage: 11.83,
      rating: 4.54,
      stock: 96,
      brand: "Infinix",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
      images: [],
    },
    {
      id: 6,
      title: "MacBook Pro",
      description: "",
      price: 1749,
      discountPercentage: 11.02,
      rating: 4.57,
      stock: 83,
      brand: "Apple",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.png",
      images: [],
    },
  ];
  test("sort rating from min to max", () => {
    expect(sortByRatingMax(send)).toEqual(expected);
  });
});
